import Head from "next/head";
import { motion } from "framer-motion-3d";
import Scene from "../components/Scene";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Next Three Tailwind</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Scene />

      
    </div>
  );
}
